---

mysql_conf_dir: "/etc/mysql/"

mysql_root_db_pass: root

mysql_db:
  - name: wordpressdb

mysql_users:
  - name: wpuser
    pass: wpuser
    priv: "*.*:ALL"

mysql_packages:
  - python-selinux
  - mysql-server
  - python-mysqldb